import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Brain,
  TrendingUp,
  TrendingDown,
  Target,
  Sparkles,
  Download,
  Share2,
  Calendar,
  Clock,
  CheckCircle2,
  AlertTriangle,
  ChevronRight,
  Loader2,
  RefreshCw,
  BarChart3,
  Zap,
} from 'lucide-react';
import { useWeeklyReport, useRegenerateWeeklyReport } from '@/hooks/useAI';

interface WeeklyReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  weekOffset?: number;
}

export function WeeklyReportModal({ isOpen, onClose, weekOffset = 0 }: WeeklyReportModalProps) {
  const { data: report, isLoading, error } = useWeeklyReport(weekOffset);
  const regenerate = useRegenerateWeeklyReport();
  const [activeTab, setActiveTab] = useState<'overview' | 'trends' | 'goals'>('overview');

  const handleRegenerate = () => {
    regenerate.mutate(weekOffset);
  };

  const handleDownloadPDF = () => {
    // Create printable content
    const printWindow = window.open('', '_blank');
    if (!printWindow || !report) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Weekly Productivity Report - ${report.week_start} to ${report.week_end}</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #1a1a2e; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
            h2 { color: #374151; margin-top: 30px; }
            .summary { background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; }
            .metric { display: inline-block; margin-right: 40px; margin-bottom: 15px; }
            .metric-value { font-size: 24px; font-weight: bold; color: #7c3aed; }
            .metric-label { font-size: 12px; color: #6b7280; }
            ul { padding-left: 20px; }
            li { margin-bottom: 8px; color: #374151; }
            .trend-up { color: #10b981; }
            .trend-down { color: #ef4444; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
          </style>
        </head>
        <body>
          <h1>Weekly Productivity Report</h1>
          <p>${report.week_start} to ${report.week_end}</p>

          <div class="summary">
            <h2 style="margin-top: 0;">Executive Summary</h2>
            <p>${report.executive_summary}</p>
          </div>

          <div>
            <div class="metric">
              <div class="metric-value">${Math.round(report.average_productivity_score)}%</div>
              <div class="metric-label">Average Productivity</div>
            </div>
            <div class="metric">
              <div class="metric-value">${(report.total_productive_hours ?? 0).toFixed(1)}h</div>
              <div class="metric-label">Productive Hours</div>
            </div>
            <div class="metric">
              <div class="metric-value">${(report.total_tracked_hours ?? 0).toFixed(1)}h</div>
              <div class="metric-label">Total Tracked</div>
            </div>
          </div>

          <h2>Key Achievements</h2>
          <ul>
            ${(report.achievements ?? []).map(a => `<li>${a}</li>`).join('')}
          </ul>

          <h2>Areas for Improvement</h2>
          <ul>
            ${(report.challenges ?? []).map(c => `<li>${c}</li>`).join('')}
          </ul>

          <h2>Trends</h2>
          <ul>
            ${(report.trends ?? []).map(t => `<li class="${t.direction === 'up' ? 'trend-up' : t.direction === 'down' ? 'trend-down' : ''}">${t.metric}: ${(t.change ?? 0) > 0 ? '+' : ''}${t.change ?? 0}% ${t.insight ?? ''}</li>`).join('')}
          </ul>

          <h2>Next Week's Goals</h2>
          <ul>
            ${(report.goals ?? []).map(g => `<li><strong>${g.title}</strong>: ${g.description}</li>`).join('')}
          </ul>

          <div class="footer">
            <p>Generated by Productify Pro AI • ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.print();
  };

  const handleShare = async () => {
    if (!report) return;

    const shareText = `Weekly Productivity Report (${report.week_start} to ${report.week_end})\n\n${report.executive_summary}\n\nProductivity Score: ${Math.round(report.average_productivity_score ?? 0)}%\nProductive Hours: ${(report.total_productive_hours ?? 0).toFixed(1)}h`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Weekly Productivity Report',
          text: shareText,
        });
      } catch (err) {
        // User cancelled or error
      }
    } else {
      // Fallback: copy to clipboard
      await navigator.clipboard.writeText(shareText);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="fixed inset-4 md:inset-10 lg:inset-20 z-50 flex items-center justify-center"
          >
            <div className="w-full h-full max-w-5xl bg-gradient-to-br from-gray-900 to-gray-950 rounded-2xl border border-white/10 shadow-2xl overflow-hidden flex flex-col">
              {/* Header */}
              <div className="flex items-center justify-between p-6 border-b border-white/10">
                <div className="flex items-center gap-4">
                  <div className="p-3 rounded-xl bg-gradient-to-br from-accent/20 to-purple-500/20">
                    <Brain className="text-accent" size={28} />
                  </div>
                  <div>
                    <h2 className="text-xl font-semibold text-white">Weekly AI Report</h2>
                    {report && (
                      <p className="text-white/50 text-sm">
                        {report.week_start} to {report.week_end}
                      </p>
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  {report && (
                    <>
                      <button
                        onClick={handleDownloadPDF}
                        className="p-2 rounded-lg bg-white/5 text-white/60 hover:text-white hover:bg-white/10 transition-colors"
                        title="Download PDF"
                      >
                        <Download size={20} />
                      </button>
                      <button
                        onClick={handleShare}
                        className="p-2 rounded-lg bg-white/5 text-white/60 hover:text-white hover:bg-white/10 transition-colors"
                        title="Share"
                      >
                        <Share2 size={20} />
                      </button>
                      <button
                        onClick={handleRegenerate}
                        disabled={regenerate.isPending}
                        className="p-2 rounded-lg bg-white/5 text-white/60 hover:text-white hover:bg-white/10 transition-colors disabled:opacity-50"
                        title="Regenerate"
                      >
                        <RefreshCw size={20} className={regenerate.isPending ? 'animate-spin' : ''} />
                      </button>
                    </>
                  )}
                  <button
                    onClick={onClose}
                    className="p-2 rounded-lg bg-white/5 text-white/60 hover:text-white hover:bg-white/10 transition-colors"
                  >
                    <X size={20} />
                  </button>
                </div>
              </div>

              {/* Content */}
              <div className="flex-1 overflow-y-auto p-6">
                {isLoading ? (
                  <div className="flex flex-col items-center justify-center h-full gap-4">
                    <Loader2 className="animate-spin text-accent" size={48} />
                    <p className="text-white/60">Generating your weekly report...</p>
                    <p className="text-white/40 text-sm">This may take a moment</p>
                  </div>
                ) : error || !report ? (
                  <div className="flex flex-col items-center justify-center h-full gap-4">
                    <AlertTriangle className="text-red-400" size={48} />
                    <p className="text-white/60">Unable to generate weekly report</p>
                    <button
                      onClick={handleRegenerate}
                      className="px-4 py-2 rounded-lg bg-accent text-white hover:bg-accent/80 transition-colors"
                    >
                      Try Again
                    </button>
                  </div>
                ) : (
                  <div className="space-y-6">
                    {/* Tabs */}
                    <div className="flex gap-2 p-1 bg-white/5 rounded-lg w-fit">
                      {(['overview', 'trends', 'goals'] as const).map((tab) => (
                        <button
                          key={tab}
                          onClick={() => setActiveTab(tab)}
                          className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${
                            activeTab === tab
                              ? 'bg-accent text-white'
                              : 'text-white/60 hover:text-white'
                          }`}
                        >
                          {tab.charAt(0).toUpperCase() + tab.slice(1)}
                        </button>
                      ))}
                    </div>

                    <AnimatePresence mode="wait">
                      {activeTab === 'overview' && (
                        <motion.div
                          key="overview"
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -10 }}
                          className="space-y-6"
                        >
                          {/* Executive Summary */}
                          <div className="p-6 rounded-xl bg-gradient-to-br from-accent/10 to-purple-500/10 border border-accent/20">
                            <div className="flex items-center gap-2 mb-3">
                              <Sparkles className="text-accent" size={18} />
                              <h3 className="text-white font-medium">Executive Summary</h3>
                            </div>
                            <p className="text-white/80 text-lg leading-relaxed">
                              {report.executive_summary}
                            </p>
                          </div>

                          {/* Key Metrics */}
                          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                            <MetricCard
                              icon={<BarChart3 className="text-accent" size={20} />}
                              label="Avg. Productivity"
                              value={`${Math.round(report.average_productivity_score ?? 0)}%`}
                              trend={report.productivity_trend}
                            />
                            <MetricCard
                              icon={<Clock className="text-blue-400" size={20} />}
                              label="Productive Hours"
                              value={`${(report.total_productive_hours ?? 0).toFixed(1)}h`}
                            />
                            <MetricCard
                              icon={<Calendar className="text-purple-400" size={20} />}
                              label="Total Tracked"
                              value={`${(report.total_tracked_hours ?? 0).toFixed(1)}h`}
                            />
                            <MetricCard
                              icon={<Zap className="text-yellow-400" size={20} />}
                              label="Best Day"
                              value={report.best_day || 'N/A'}
                            />
                          </div>

                          {/* Achievements & Challenges */}
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="glass-card p-5">
                              <div className="flex items-center gap-2 mb-4">
                                <CheckCircle2 className="text-productive" size={18} />
                                <h4 className="text-white font-medium">Key Achievements</h4>
                              </div>
                              <ul className="space-y-2">
                                {(report.achievements ?? []).map((achievement, index) => (
                                  <motion.li
                                    key={index}
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: index * 0.1 }}
                                    className="flex items-start gap-2 text-sm"
                                  >
                                    <CheckCircle2 className="text-productive flex-shrink-0 mt-0.5" size={14} />
                                    <span className="text-white/80">{achievement}</span>
                                  </motion.li>
                                ))}
                                {(!report.achievements || report.achievements.length === 0) && (
                                  <li className="text-white/40 text-sm">No achievements recorded</li>
                                )}
                              </ul>
                            </div>

                            <div className="glass-card p-5">
                              <div className="flex items-center gap-2 mb-4">
                                <Target className="text-yellow-400" size={18} />
                                <h4 className="text-white font-medium">Challenges</h4>
                              </div>
                              <ul className="space-y-2">
                                {(report.challenges ?? []).map((challenge, index) => (
                                  <motion.li
                                    key={index}
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: index * 0.1 }}
                                    className="flex items-start gap-2 text-sm"
                                  >
                                    <ChevronRight className="text-yellow-400 flex-shrink-0 mt-0.5" size={14} />
                                    <span className="text-white/80">{challenge}</span>
                                  </motion.li>
                                ))}
                                {(!report.challenges || report.challenges.length === 0) && (
                                  <li className="text-white/40 text-sm">No challenges recorded</li>
                                )}
                              </ul>
                            </div>
                          </div>

                          {/* AI Analysis */}
                          {report.ai_analysis && (
                            <div className="p-5 rounded-xl bg-white/5 border border-white/10">
                              <div className="flex items-center gap-2 mb-3">
                                <Brain className="text-purple-400" size={18} />
                                <h4 className="text-white font-medium">AI Analysis</h4>
                              </div>
                              <p className="text-white/70">{report.ai_analysis}</p>
                            </div>
                          )}
                        </motion.div>
                      )}

                      {activeTab === 'trends' && (
                        <motion.div
                          key="trends"
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -10 }}
                          className="space-y-6"
                        >
                          <h3 className="text-white font-medium">Weekly Trends</h3>

                          <div className="grid gap-4">
                            {(report.trends ?? []).length > 0 ? (
                              (report.trends ?? []).map((trend, index) => (
                                <motion.div
                                  key={index}
                                  initial={{ opacity: 0, y: 10 }}
                                  animate={{ opacity: 1, y: 0 }}
                                  transition={{ delay: index * 0.1 }}
                                  className="glass-card p-4"
                                >
                                  <div className="flex items-center justify-between mb-2">
                                    <span className="text-white font-medium">{trend.metric}</span>
                                    <div className={`flex items-center gap-1 ${
                                      trend.direction === 'up' ? 'text-productive' :
                                      trend.direction === 'down' ? 'text-red-400' :
                                      'text-white/50'
                                    }`}>
                                      {trend.direction === 'up' ? (
                                        <TrendingUp size={16} />
                                      ) : trend.direction === 'down' ? (
                                        <TrendingDown size={16} />
                                      ) : null}
                                      <span className="font-semibold">
                                        {(trend.change ?? 0) > 0 ? '+' : ''}{trend.change ?? 0}%
                                      </span>
                                    </div>
                                  </div>
                                  <p className="text-white/60 text-sm">{trend.insight}</p>
                                </motion.div>
                              ))
                            ) : (
                              <div className="text-white/40 text-center py-8">No trends available</div>
                            )}
                          </div>

                          {/* Comparison */}
                          {report.comparison_to_previous && (
                            <div className="p-5 rounded-xl bg-white/5 border border-white/10">
                              <h4 className="text-white font-medium mb-3">Compared to Last Week</h4>
                              <p className="text-white/70">{report.comparison_to_previous}</p>
                            </div>
                          )}
                        </motion.div>
                      )}

                      {activeTab === 'goals' && (
                        <motion.div
                          key="goals"
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -10 }}
                          className="space-y-6"
                        >
                          <h3 className="text-white font-medium">Goals for Next Week</h3>

                          <div className="grid gap-4">
                            {(report.goals ?? []).length > 0 ? (
                              (report.goals ?? []).map((goal, index) => (
                                <motion.div
                                  key={index}
                                  initial={{ opacity: 0, y: 10 }}
                                  animate={{ opacity: 1, y: 0 }}
                                  transition={{ delay: index * 0.1 }}
                                  className="glass-card p-5"
                                >
                                  <div className="flex items-start gap-4">
                                    <div className="p-2 rounded-lg bg-accent/20 text-accent">
                                      <Target size={20} />
                                    </div>
                                    <div className="flex-1">
                                      <h4 className="text-white font-medium mb-1">{goal.title}</h4>
                                      <p className="text-white/60 text-sm mb-3">{goal.description}</p>
                                      {goal.target && (
                                        <div className="flex items-center gap-2 text-sm">
                                          <span className="text-white/40">Target:</span>
                                          <span className="text-accent font-medium">{goal.target}</span>
                                        </div>
                                      )}
                                    </div>
                                    {goal.priority && (
                                      <span className={`px-2 py-1 rounded-full text-xs ${
                                        goal.priority === 'high' ? 'bg-red-500/20 text-red-400' :
                                        goal.priority === 'medium' ? 'bg-yellow-500/20 text-yellow-400' :
                                        'bg-green-500/20 text-green-400'
                                      }`}>
                                        {goal.priority}
                                      </span>
                                    )}
                                  </div>
                                </motion.div>
                              ))
                            ) : (
                              <div className="text-white/40 text-center py-8">No goals set yet</div>
                            )}
                          </div>

                          {/* Recommendations */}
                          {report.recommendations && report.recommendations.length > 0 && (
                            <div className="p-5 rounded-xl bg-gradient-to-br from-purple-500/10 to-pink-500/10 border border-purple-500/20">
                              <div className="flex items-center gap-2 mb-4">
                                <Sparkles className="text-purple-400" size={18} />
                                <h4 className="text-white font-medium">AI Recommendations</h4>
                              </div>
                              <ul className="space-y-2">
                                {report.recommendations.map((rec, index) => (
                                  <li key={index} className="flex items-start gap-2 text-sm">
                                    <ChevronRight className="text-purple-400 flex-shrink-0 mt-0.5" size={14} />
                                    <span className="text-white/80">{rec}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                )}
              </div>

              {/* Footer */}
              {report && (
                <div className="px-6 py-4 border-t border-white/10 bg-white/5">
                  <div className="flex items-center justify-between text-xs text-white/40">
                    <span className="flex items-center gap-1">
                      <Sparkles size={12} />
                      AI-powered analysis by Productify Pro
                    </span>
                    <span>
                      Generated {new Date(report.generated_at).toLocaleString()}
                    </span>
                  </div>
                </div>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}

// Metric Card Component
function MetricCard({
  icon,
  label,
  value,
  trend,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  trend?: 'up' | 'down' | 'stable';
}) {
  return (
    <div className="glass-card p-4">
      <div className="flex items-center gap-2 mb-2">
        {icon}
        <span className="text-white/50 text-xs">{label}</span>
      </div>
      <div className="flex items-center gap-2">
        <span className="text-white text-2xl font-bold">{value}</span>
        {trend && (
          <span className={trend === 'up' ? 'text-productive' : trend === 'down' ? 'text-red-400' : 'text-white/40'}>
            {trend === 'up' ? <TrendingUp size={16} /> : trend === 'down' ? <TrendingDown size={16} /> : null}
          </span>
        )}
      </div>
    </div>
  );
}

export default WeeklyReportModal;
